### ISSUE TITLE
how does proxy url work?

### ISSUE THREAD

**Issue by leolivier** [tsamaya/opencage-api-client#6]
Hi @tsamaya 
Thank you for this javascript library.
Can you explain somewhere how proxyUrl is working? You give some examples of the API using this but I don't understand what the proxy should send. If it's the API key, then what's the use? You can steal the key by running the proxy url, no?

**Comment by tsamaya** [comment]
Hi @leolivier ,
did you have a look the sample https://github.com/tsamaya/opencage-api-client/blob/master/samples/node-proxy-sample.js ?
In my other repositories you will find code to deploy [AWS lambda](https://github.com/tsamaya/aws-lambda-opencage-geocoder) and [Google Cloud Functions](https://github.com/tsamaya/gcloud-functions-opencage-geocoder) in order to proxy the request. But a simple PHP page taking the request and adding your Opencage Data API Key is far enough as well.
Please let me know if I can help further.
